services:
  php:
    image: zenith/php8composer
    container_name: recipe_php
    volumes:
      - ./code:/code
      - ./database:/database
      - ./entrypoint.sh:/entrypoint.sh
    working_dir: /code
    env_file: ./.env
    entrypoint: ["/bin/sh", "/entrypoint.sh"]

  nginx:
    image: nginx:latest
    container_name: recipe_web
    ports:
      - 8080:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./code:/code
